import type { ComponentProps } from 'react';
import { Icon } from '@iconify/react';
import type { IconifyIcon } from '@iconify/types';
import airportSecurity from '@iconify-icons/streamline-plump/airport-security-remix';
import arrowCircle1 from '@iconify-icons/streamline-plump/arrow-right-circle-1';
import arrowCircle2 from '@iconify-icons/streamline-plump/arrow-right-circle-2';
import bag from '@iconify-icons/streamline-plump/bag-remix';
import calendarCheck from '@iconify-icons/streamline-plump/calendar-check-remix';
import calendarMark from '@iconify-icons/streamline-plump/calendar-mark-remix';
import camera from '@iconify-icons/streamline-plump/camera-1-remix';
import checkThick from '@iconify-icons/streamline-plump/check-thick-remix';
import clock from '@iconify-icons/streamline-plump/circle-clock-remix';
import clean from '@iconify-icons/streamline-plump/clean-broom-wipe-remix';
import clipboard from '@iconify-icons/streamline-plump/empty-clipboard-remix';
import cog from '@iconify-icons/streamline-plump/cog-1-remix';
import door from '@iconify-icons/streamline-plump/door-remix';
import electric from '@iconify-icons/streamline-plump/electric-cord-1-remix';
import eye from '@iconify-icons/streamline-plump/eye-optic-remix';
import fileCheck from '@iconify-icons/streamline-plump/file-check-alternate-remix';
import help from '@iconify-icons/streamline-plump/help-chat-1';
import home from '@iconify-icons/streamline-plump/home-1-remix';
import image from '@iconify-icons/streamline-plump/image-saturation-vertical-remix';
import layers from '@iconify-icons/streamline-plump/layers-1-remix';
import leaf from '@iconify-icons/streamline-plump/leaf-protect-remix';
import lightning from '@iconify-icons/streamline-plump/lightning-cloud-remix';
import location from '@iconify-icons/streamline-plump/location-pin-remix';
import lock from '@iconify-icons/streamline-plump/keyhole-lock-circle-remix';
import login from '@iconify-icons/streamline-plump/login-1-remix';
import mail from '@iconify-icons/streamline-plump/mail-notification-remix';
import mailCheck from '@iconify-icons/streamline-plump/mail-send-email-message-remix';
import mapLocation from '@iconify-icons/streamline-plump/map-location-star-pin-remix';
import menu from '@iconify-icons/streamline-plump/drop-down-menu-remix';
import message from '@iconify-icons/streamline-plump/chat-bubble-text-square-remix';
import money from '@iconify-icons/streamline-plump/money-cash-bill-1';
import more from '@iconify-icons/streamline-plump/horizontal-menu-circle-remix';
import paint from '@iconify-icons/streamline-plump/paint-bucket-remix';
import paintbrush from '@iconify-icons/streamline-plump/paintbrush-2-remix';
import panel from '@iconify-icons/streamline-plump/layout-window-4-remix';
import phone from '@iconify-icons/streamline-plump/phone-remix';
import pinwheel from '@iconify-icons/streamline-plump/pinwheel-remix';
import receiptCross from '@iconify-icons/streamline-plump/receipt-cross-remix';
import search from '@iconify-icons/streamline-plump/search-visual-remix';
import send from '@iconify-icons/streamline-plump/mail-send-remix';
import shield from '@iconify-icons/streamline-plump/shield-1-remix';
import slider from '@iconify-icons/streamline-plump/horizontal-slider-square-remix';
import sparkles from '@iconify-icons/streamline-plump/multiple-stars-remix';
import star from '@iconify-icons/streamline-plump/star-circle-remix';
import starMedal from '@iconify-icons/streamline-plump/star-medal-1-remix';
import stool from '@iconify-icons/streamline-plump/stool-remix';
import tag from '@iconify-icons/streamline-plump/tag-alt-remix';
import toolBox from '@iconify-icons/streamline-plump/tool-box-remix';
import trending from '@iconify-icons/streamline-plump/graph-arrow-user-increase-remix';
import truck from '@iconify-icons/streamline-plump/food-truck-event-fair-remix';
import user from '@iconify-icons/streamline-plump/user-face-male-remix';
import userRound from '@iconify-icons/streamline-plump/office-worker-remix';
import wrench from '@iconify-icons/streamline-plump/wrench-circle-remix';

type IconProps = Omit<ComponentProps<typeof Icon>, 'icon'> & { size?: number | string; strokeWidth?: number };
const createIcon = (icon: IconifyIcon, rotation = 0) => ({ size = 20, width, height, strokeWidth: _strokeWidth, ...props }: IconProps) => <Icon icon={icon} width={width ?? size} height={height ?? size} rotate={rotation} {...props} />;

export const AirVent=createIcon(lightning), Armchair=createIcon(stool), ArrowDown=createIcon(arrowCircle2, 1), ArrowLeft=createIcon(arrowCircle2, 2), ArrowRight=createIcon(arrowCircle2);
export const BadgeCheck=createIcon(starMedal), Bell=createIcon(message), Bolt=createIcon(electric), BrickWall=createIcon(layers), Briefcase=createIcon(bag), BriefcaseBusiness=createIcon(toolBox), Brush=createIcon(paintbrush);
export const Calendar=createIcon(calendarMark), Camera=createIcon(camera), Check=createIcon(checkThick), CheckCircle=createIcon(calendarCheck), CheckIcon=Check, ChevronDown=createIcon(arrowCircle1, 1), ChevronDownIcon=ChevronDown, ChevronLeft=createIcon(arrowCircle1, 2), ChevronRight=createIcon(arrowCircle1), ChevronRightIcon=ChevronRight;
export const Circle=createIcon(star), CircleDollarSign=createIcon(money), CircleIcon=Circle, ClipboardCheck=createIcon(fileCheck), ClipboardList=createIcon(clipboard), Clock=createIcon(clock), Eye=createIcon(eye), Fan=createIcon(pinwheel), GripVerticalIcon=createIcon(more);
export const Hammer=createIcon(wrench), HardHat=createIcon(shield), Heart=createIcon(star), HelpCircle=createIcon(help), Home=createIcon(home), Image=createIcon(image), KeyRound=createIcon(lock), Leaf=createIcon(leaf), LockKeyhole=createIcon(lock), LogIn=createIcon(login), LogOut=createIcon(door);
export const Mail=createIcon(mail), MailCheck=createIcon(mailCheck), MapPin=createIcon(location), Menu=createIcon(menu), MessageCircle=createIcon(message), MoreHorizontal=createIcon(more), Navigation=createIcon(mapLocation), PaintRoller=createIcon(paint), PanelLeftIcon=createIcon(panel), Phone=createIcon(phone);
export const Search=createIcon(search), Send=createIcon(send), Settings=createIcon(cog), Shield=createIcon(shield), ShieldCheck=createIcon(airportSecurity), SlidersHorizontal=createIcon(slider), Sparkles=createIcon(sparkles), SprayCan=createIcon(clean), Star=createIcon(star), Tag=createIcon(tag), TrendingUp=createIcon(trending), Truck=createIcon(truck);
export const User=createIcon(user), UserRound=createIcon(userRound), Wrench=createIcon(wrench), X=createIcon(receiptCross), XIcon=X, Zap=Bolt;
